export const NewsDummyData = [
  {
    id: 0,
    title: "당신의 '아침 루틴' 궁금하다",
    content: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://picsum.photos/700/400",
    views: 132,
  },
  {
    id: 1,
    title: "당신의 '교복 스탠다드' 궁금하다",
    content: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/any",
    views: 10,
  },
  {
    id: 2,
    title: "당신의 '스터디 스타일' 궁금하다",
    content: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/sepia",
    views: 12,
  },
  {
    id: 3,
    title: "당신의 '직업 적성' 궁금하다",
    content: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/tech",
    views: 15,
  },
  {
    id: 4,
    title: "당신의 '취미 생활' 궁금하다",
    content: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/people",
    views: 16,
  },
  {
    id: 5,
    title: "당신의 '등교 루트' 궁금하다",
    content: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/nature",
    views: 17,
  },
  {
    id: 6,
    title: "당신의 '아침 루틴' 궁금하다",
    content: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://picsum.photos/700/400",
    views: 132,
  },
  {
    id: 7,
    title: "당신의 '교복 스탠다드' 궁금하다",
    content: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/any",
    views: 10,
  },
  {
    id: 8,
    title: "당신의 '스터디 스타일' 궁금하다",
    content: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/sepia",
    views: 12,
  },
  {
    id: 9,
    title: "당신의 '직업 적성' 궁금하다",
    content: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/tech",
    views: 15,
  },
  {
    id: 10,
    title: "당신의 '취미 생활' 궁금하다",
    content: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/people",
    views: 16,
  },
  {
    id: 11,
    title: "당신의 '등교 루트' 궁금하다",
    content: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/nature",
    views: 17,
  },
];

export default NewsDummyData;
