export const NewsDummyData = [
  {
    newsId: 0,
    newsTitle: "당신의 '아침 루틴' 궁금하다",
    newsContent: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://picsum.photos/700/400",
    newsViews: 132,
  },
  {
    newsId: 1,
    newsTitle: "당신의 '교복 스탠다드' 궁금하다",
    newsContent: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/any",
    newsViews: 10,
  },
  {
    newsId: 2,
    newsTitle: "당신의 '스터디 스타일' 궁금하다",
    newsContent: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/sepia",
    newsViews: 12,
  },
  {
    newsId: 3,
    newsTitle: "당신의 '직업 적성' 궁금하다",
    newsContent: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/tech",
    newsViews: 15,
  },
  {
    newsId: 4,
    newsTitle: "당신의 '취미 생활' 궁금하다",
    newsContent: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/people",
    newsViews: 16,
  },
  {
    newsId: 5,
    newsTitle: "당신의 '등교 루트' 궁금하다",
    newsContent: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/nature",
    newsViews: 17,
  },
  {
    newsId: 6,
    newsTitle: "당신의 '아침 루틴' 궁금하다",
    newsContent: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://picsum.photos/700/400",
    newsViews: 132,
  },
  {
    newsId: 7,
    newsTitle: "당신의 '교복 스탠다드' 궁금하다",
    newsContent: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/any",
    newsViews: 10,
  },
  {
    newsId: 8,
    newsTitle: "당신의 '스터디 스타일' 궁금하다",
    newsContent: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/sepia",
    newsViews: 12,
  },
  {
    newsId: 9,
    newsTitle: "당신의 '직업 적성' 궁금하다",
    newsContent: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/tech",
    newsViews: 15,
  },
  {
    newsId: 10,
    newsTitle: "당신의 '취미 생활' 궁금하다",
    newsContent: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/people",
    newsViews: 16,
  },
  {
    newsId: 11,
    newsTitle: "당신의 '등교 루트' 궁금하다",
    newsContent: "뉴스 기사",
    writer: "HIGHWAY TIMES",
    src: "https://placeimg.com/700/400/nature",
    newsViews: 17,
  },
];

export default NewsDummyData;
