export const VideoDummyData = [
  {
    id: 0,
    title: "근명고등학교 홍보영상",
    content: "근명 고등학교",
    src: "https://www.youtube.com/embed/fgs6lBS1TEQ",
    image: "https://img.youtube.com/vi/fgs6lBS1TEQ/0.jpg",
    views: 132,
  },
  {
    id: 1,
    title: "안양 공업 고등학교 홍보영상",
    content: "안양 공업 고등학교",
    src: "https://www.youtube.com/embed/Qh7vK4QXR4A",
    image: "https://img.youtube.com/vi/Qh7vK4QXR4A/0.jpg",
    views: 10,
  },
  {
    id: 2,
    title: "안양 문화 고등학교 홍보영상",
    content: "안양 문화 고등학교",
    src: "https://www.youtube.com/embed/v0NtB8-wri4",
    image: "https://img.youtube.com/vi/v0NtB8-wri4/0.jpg",
    views: 15,
  },
  {
    id: 3,
    title: "경기 폴리텍 고등학교 홍보영상",
    content: "경기 폴리텍 고등학교",
    src: "https://www.youtube.com/embed/3e_N6K4Am1U",
    image: "https://img.youtube.com/vi/3e_N6K4Am1U/0.jpg",
    views: 15,
  },
  {
    id: 4,
    title: "군포 e비즈니스 고등학교 홍보영상",
    content: "군포 e비즈니스 고등학교",
    src: "https://www.youtube.com/embed/FB2_JG9y-_I",
    image: "https://img.youtube.com/vi/FB2_JG9y-_I/0.jpg",
    views: 16,
  },
  {
    id: 5,
    title: "근명고등학교 홍보영상",
    content: "근명 고등학교",
    src: "https://www.youtube.com/embed/fgs6lBS1TEQ",
    image: "https://img.youtube.com/vi/fgs6lBS1TEQ/0.jpg",
    views: 132,
  },
  {
    id: 6,
    title: "안양 공업 고등학교 홍보영상",
    content: "안양 공업 고등학교",
    src: "https://www.youtube.com/embed/Qh7vK4QXR4A",
    image: "https://img.youtube.com/vi/Qh7vK4QXR4A/0.jpg",
    views: 10,
  },
  {
    id: 7,
    title: "안양 문화 고등학교 홍보영상",
    content: "안양 문화 고등학교",
    src: "https://www.youtube.com/embed/v0NtB8-wri4",
    image: "https://img.youtube.com/vi/v0NtB8-wri4/0.jpg",
    views: 15,
  },
  {
    id: 8,
    title: "경기 폴리텍 고등학교 홍보영상",
    content: "경기 폴리텍 고등학교",
    src: "https://www.youtube.com/embed/3e_N6K4Am1U",
    image: "https://img.youtube.com/vi/3e_N6K4Am1U/0.jpg",
    views: 15,
  },
  {
    id: 9,
    title: "군포 e비즈니스 고등학교 홍보영상",
    content: "군포 e비즈니스 고등학교",
    src: "https://www.youtube.com/embed/FB2_JG9y-_I",
    image: "https://img.youtube.com/vi/FB2_JG9y-_I/0.jpg",
    views: 16,
  },
];

export default VideoDummyData;
