export const CHECK_DUPLICATE_ID_REQUEST = "USER/CHECK_DUPLICATE_ID_REQUEST";
export const CHECK_DUPLICATE_ID_SUCCESS = "USER/CHECK_DUPLICATE_ID_SUCCESS";
export const CHECK_DUPLICATE_ID_FAILURE = "USER/CHECK_DUPLICATE_ID_FAILURE";

export const LOGIN_REQUEST = "USER/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USER/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USER/LOGIN_FAILURE";

export const SIGNUP_REQUEST = "USER/SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "USER/SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "USER/SIGNUP_FAILURE";

export const LOGOUT_REQUEST = "USER/LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "USER/LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "USER/LOGOUT_FAILURE";

export const LOAD_USER_REQUEST = "USER/LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "USER/LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "USER/LOAD_USER_FAILURE";

export const SWITCH_DARK_MODE = "USER/SWITCH_DARK_MODE";
export const SWITCH_LIGHT_MODE = "USER/SWITCH_LIGHT_MODE";

export const REFRESH_TOKEN_REQUEST = "USER/REFRESH_TOKEN_REQUEST";
export const REFRESH_TOKEN_SUCCESS = "USER/REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAILURE = "USER/REFRESH_TOKEN_FAILURE";

export const LOAD_SCHOOL_LIST_REQUEST = "SCHOOL/LOAD_SCHOOL_LIST_REQUEST";
export const LOAD_SCHOOL_LIST_SUCCESS = "SCHOOL/LOAD_SCHOOL_LIST_SUCCESS";
export const LOAD_SCHOOL_LIST_FAILURE = "SCHOOL/LOAD_SCHOOL_LIST_FAILURE";

export const LOAD_SCHOOL_INFO_REQUEST = "SCHOOL/LOAD_SCHOOL_INFO_REQUEST";
export const LOAD_SCHOOL_INFO_SUCCESS = "SCHOOL/LOAD_SCHOOL_INFO_SUCCESS";
export const LOAD_SCHOOL_INFO_FAILURE = "SCHOOL/LOAD_SCHOOL_INFO_FAILURE";

export const ADD_REVIEW_SUCCESS = "SCHOOL/ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAILURE = "SCHOOL/ADD_REVIEW_FAILURE";
export const ADD_REVIEW_REQUEST = "SCHOOL/ADD_REVIEW_REQUEST";
