export const CHECK_USER_ID_REQUEST = "USER/CHECK_USER_ID_REQUEST";
export const CHECK_USER_ID_SUCCESS = "USER/CHECK_USER_ID_SUCCESS";
export const CHECK_USER_ID_FAILURE = "USER/CHECK_USER_ID_FAILURE";
